controller_list:
  - name: fake_arm_controller
    joints:
      - waist
      - shoulder
      - elbow
      - wrist_angle
      - wrist_rotate
  - name: fake_gripper_controller
    joints:
      - left_finger
