arm_controller:
  action_ns: /wx200/arm_controller/follow_joint_trajectory/status
  type: position_controllers/JointTrajectoryController
  joints:
    - waist
    - shoulder
    - elbow
    - wrist_angle
    - wrist_rotate
  constraints:
    goal_time: 1
    stopped_velocity_tolerance: 0.02

gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - left_finger
